data = [
        {"category": "Science & Nature",
         "type": "boolean",
         "difficulty": "medium",
         "question": "A person can get sunburned on a cloudy day.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The Great Wall of China is visible from the moon.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "A slug&rsquo;s blood is green.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "The flag of South Africa features 7 colours.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
         "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the first music video to broadcast on MTV.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "Nutella is produced by the German company Ferrero.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "hard",
         "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
         "question": "The binary number &quot;101001101&quot; is equivalent to the Decimal number &quot;334&quot;",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
         "difficulty": "easy",
         "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "medium",
         "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Kissing someone for one minute burns about 2 calories.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "easy",
         "question": "Roger Federer is a famous soccer player.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "An Astronomical Unit is the distance between Earth and the Moon.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "3 members of 2 Live Crew were arrested for playing songs from their album, As Nasty As They Wanna Be, live.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Politics", "type": "boolean", "difficulty": "easy",
         "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "medium",
         "question": "David Baszucki was a co-founder of ROBLOX Corporation.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Politics", "type": "boolean", "difficulty": "medium",
         "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean",
         "difficulty": "easy",
         "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
         "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
         "difficulty": "easy",
         "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "easy",
         "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "medium",
         "question": "Hidden in the files for &quot;Mario Kart Arcade GP&quot; is a picture of the Beslan school hostage crisis.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean",
         "difficulty": "medium",
         "question": "An episode of &quot;The Simpsons&quot; is dedicated to Moe Szyslak&#039;s bar rag.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The National Animal of Scotland is the Unicorn.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "The United States of America was the first country to launch a man into space.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "A plant that has a life cycle for more than a year is known as an annual.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean",
         "difficulty": "hard",
         "question": "In &quot;Minecraft&quot;, gold tools are faster than diamond tools.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean",
         "difficulty": "easy",
         "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
         "question": "The original ending of &quot;Little Shop Of Horrors&quot; has the plants taking over the world.",
         "correct_answer": "True", "incorrect_answers": ["False"]}
    ]
